# Define headers for different deployment contexts
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "${URL}"
    
[[headers]]
  for = "/.netlify/functions/*"
  condition = "deploy-preview"
  [headers.values]
    Access-Control-Allow-Origin = "${DEPLOY_URL}"

[[headers]]
  for = "/.netlify/functions/*"
  condition = "branch-deploy"
  [headers.values]
    Access-Control-Allow-Origin = "${DEPLOY_URL}"

[[headers]]
  for = "/.netlify/functions/*"
  condition = "dev"
  [headers.values]
    Access-Control-Allow-Origin = "http://localhost:5173"
    